name: auto-merge
on:
  pull_request:
    types:
      - opened
      - ready_to_merge
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  # 合并发布版本的 pr 到 main
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Merge The Created PR
        uses: 'pascalgn/automerge-action@v0.15.6'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: ''
          # 只要是 lwsgh 用户，都进行合并
          MERGE_FILTER_AUTHOR: 'lwsgh'